global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'alert_receiver'

receivers:
  - name: 'alert_receiver'
    webhook_configs:
      - url: 'http://localhost:3456/alert'
        send_resolved: true 