name: Monitoring Integration

on:
  push:
    branches: [ main, develop, youtube-collector-fixes ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      prometheus:
        image: prom/prometheus:v2.30.3
        ports:
          - 9090:9090
      alertmanager:
        image: prom/alertmanager:v0.23.0
        ports:
          - 9093:9093

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Set up monitoring configuration
      run: |
        mkdir -p monitoring/prometheus
        cp prometheus/prometheus.yml monitoring/prometheus/
        cp prometheus/alert.rules monitoring/prometheus/
        chmod -R 777 monitoring/prometheus

    - name: Run monitoring tests
      env:
        PROMETHEUS_URL: http://localhost:9090
        ALERTMANAGER_URL: http://localhost:9093
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      run: |
        pytest monitoring/tests/ -v

    - name: Validate alert rules
      run: |
        python monitoring/scripts/update_alert_rules.py --validate-only

    - name: Test threshold optimization
      run: |
        python monitoring/scripts/optimize_thresholds.py --dry-run

    - name: Run integration tests
      env:
        YOUTUBE_API_KEY_1: ${{ secrets.YOUTUBE_API_KEY_1 }}
        YOUTUBE_API_KEY_2: ${{ secrets.YOUTUBE_API_KEY_2 }}
        YOUTUBE_API_KEY_3: ${{ secrets.YOUTUBE_API_KEY_3 }}
      run: |
        pytest backend/scripts/test_youtube_collector.py -v
        pytest backend/scripts/test_youtube_collector_mock.py -v
        pytest backend/scripts/test_production_readiness.py -v 