name: Monitoring

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  optimize-thresholds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install numpy prometheus-client

    - name: List monitoring scripts
      run: |
        echo "Listing scripts:"
        find . -name "*.py"

    - name: Optimize thresholds
      run: |
        python monitoring/scripts/optimize_thresholds.py \
          --data-path monitoring/data/metrics_history.json \
          --method percentile \
          --output-path monitoring/data/optimized_thresholds.json

    - name: Upload thresholds
      uses: actions/upload-artifact@v3
      with:
        name: optimized-thresholds
        path: monitoring/data/optimized_thresholds.json
        retention-days: 7
